name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          # https://pypi.org/project/tippecanoe/で代替
          pip install tippecanoe==2.72.0

      - name: Cache downloaded tables
        id: cache-table
        uses: actions/cache@v4
        with:
          path: table/
          key: table-2026-05-08-${{ hashFiles('scripts/00_download_csv.sh') }} # 基準値が更新されたらここを更新
          restore-keys: |
            table-

      - name: Download table
        if: steps.cache-table.outputs.cache-hit != 'true'
        run: scripts/00_download_csv.sh
        timeout-minutes: 30

      - name: Generate data
        run: scripts/01_make_geojson.sh

      - name: Generate tiles
        run: |
          scripts/02_make_tiles.sh

      - name: Build demo pages
        run: |
          npm ci
          npm run build
        env:
          VITE_APP_BASE: /${{ github.event.repository.name }}/

      - name: Copy data and tiles
        run: |
          mkdir -p sample/dist/tiles
          mkdir -p sample/dist/data
          cp tiles/*.pmtiles tiles/*.json sample/dist/tiles/
          cp -r data/* sample/dist/data/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sample/dist
